INSERT INTO public.products (marca, modelo, talla_eur, talla_us, precio, estado, colorway, imagen_url) VALUES 
('Under Armour', 'Under Armour Jet 23', 37.5, 6, 150, 'Segunda mano (Grado A)', 'Jet 23', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity', 36, 4, 165, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity', ''),
('Nike (Giannis)', 'Nike Zoom Freak 5', 37.5, 6, 179, 'Segunda mano (Grado A)', 'Nike Zoom Freak 5', ''),
('Jordan / Nike', 'Air Jordan 1 High Travis Scott', 38, 6, 199, 'Segunda mano (Grado A)', 'Air Jordan 1 High Travis Scott', ''),
('Jordan / Nike', 'Jordan Tatum 1/2', 37.5, 6, 189, 'Segunda mano (Grado A)', 'Jordan Tatum 1/2', ''),
('Nike', 'Nike Sabrina 1/2', 37.5, 6, 195, 'Segunda mano (Grado A)', 'Sabrina 1/2', ''),
('Jordan / Nike', 'Jordan Luka 2 Blanco/Rosa', 36, 4, 219, 'Segunda mano (Grado A)', 'Jordan Luka 2 Blanco/Rosa', ''),
('Jordan / Nike', 'Jordan Luka 2 Blanco/Gum', 38.5, 6, 229, 'Segunda mano (Grado A)', 'Jordan Luka 2 Blanco/Gum', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 8 Protro Purple', 38, 6, 249, 'Segunda mano (Grado A)', 'Nike Kobe 8 Protro Purple', ''),
('Nike (LeBron James)', 'Nike LeBron XXI Violet', 37.5, 6, 239, 'Segunda mano (Grado A)', 'Nike LeBron XXI Violet', ''),
('Nike (Ja Morant)', 'Nike Ja 1 Bone/Pink', 38.5, 6, 189, 'Segunda mano (Grado A)', 'Nike Ja 1 Bone/Pink', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 5 Protro PE', 39, 6.5, 239, 'Segunda mano (Grado A)', 'Nike Kobe 5 Protro PE', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 4 Amarillo/Teal', 39, 6.5, 199, 'Segunda mano (Grado A)', 'Nike Kyrie Low 4 Amarillo/Teal', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 4 Negro/Azul', 39, 7, 199, 'Segunda mano (Grado A)', 'Nike Kyrie Low 4 Negro/Azul', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Patricio Estrella SpongeBob', 39, 7, 249, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Patricio Estrella SpongeBob', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Obsidian', 39, 6.5, 209, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Obsidian', ''),
('Nike (Giannis)', 'Nike Giannis Immortality Rojo', 38.5, 6, 199, 'Segunda mano (Grado A)', 'Nike Giannis Immortality Rojo', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 6 Protro White Del Sol', 39, 6.5, 259, 'Segunda mano (Grado A)', 'z', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 4 BHM Equality', 39, 6.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie 4 BHM Equality', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Flytrap 3 Gris', 39, 6.5, 155, 'Segunda mano (Grado A)', 'Nike Kyrie Flytrap 3 Gris', ''),
('Rigorer', 'Rigorer AR1 Milky Way', 39, 6.5, 189, 'Segunda mano (Grado A)', 'AR1 Milky Way', ''),
('Rigorer', 'Rigorer AR1 Showtime', 39, 6.5, 189, 'Segunda mano (Grado A)', 'AR1 Showtime', ''),
('Li-Ning', 'Li-Ning Way of Wade 808', 39, 6.5, 199, 'Segunda mano (Grado A)', 'Way of Wade 808', ''),
('Under Armour (Curry)', 'Under Armour Curry 3Z6', 40.5, 7.5, 209, 'Segunda mano (Grado A)', 'Under Armour Curry 3Z6', ''),
('Nike (Kyrie Irving)', 'Concepts x Nike Kyrie 7 Horus', 40.5, 7.5, 259, 'Segunda mano (Grado A)', 'Concepts x Nike Kyrie 7 Horus', ''),
('Under Armour (Curry)', 'Under Armour Curry 11 Future Curry', 40.5, 7.5, 269, 'Segunda mano (Grado A)', 'Under Armour Curry 11 Future Curry', ''),
('adidas', 'adidas Trae Young Blanco/Negro', 40.5, 7.5, 249, 'Segunda mano (Grado A)', 'Trae Young Blanco/Negro', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut Blanco/Negro', 40.5, 7.5, 269, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut Blanco/Negro', ''),
('Jordan / Nike', 'Jordan Luka 2 Safari', 40.5, 7.5, 279, 'Segunda mano (Grado A)', 'Jordan Luka 2 Safari', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Celeste', 40.5, 7.5, 189, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Celeste', ''),
('Nike', 'Nike Cosmic Unity 2', 40.5, 7.5, 219, 'Segunda mano (Grado A)', 'Cosmic Unity 2', ''),
('Jordan / Nike', 'Jordan Luka 1 Negro/Volt', 40.5, 7.5, 219, 'Segunda mano (Grado A)', 'Jordan Luka 1 Negro/Volt', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut Gris/Rosa', 40, 7, 239, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut Gris/Rosa', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Just Do It', 40.5, 7.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Just Do It', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 2/3 Blanco/Celeste', 40.5, 7.5, 249, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 2/3 Blanco/Celeste', ''),
('Puma', 'Puma MB.02 Queen City LaMelo', 40, 7.5, 259, 'Segunda mano (Grado A)', 'MB.02 Queen City LaMelo', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 Expressions Weatherman', 40, 7, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 Expressions Weatherman', ''),
('Nike (Paul George)', 'Nike PG 6 What The', 40, 7, 269, 'Segunda mano (Grado A)', 'Nike PG 6 What The', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Bob Esponja XDR', 40, 7, 299, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Bob Esponja XDR', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Flytrap 4 Blanco', 40, 7, 179, 'Segunda mano (Grado A)', 'Nike Kyrie Flytrap 4 Blanco', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Blanco/Azul', 40, 7, 199, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Blanco/Azul', ''),
('Under Armour (Curry)', 'Under Armour Curry Flow 9/10', 40, 7, 219, 'Segunda mano (Grado A)', 'Under Armour Curry Flow 9/10', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 6 Oracle Aqua', 40, 7, 229, 'Segunda mano (Grado A)', 'Nike Kyrie 6 Oracle Aqua', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 6 Bred', 40, 7, 229, 'Segunda mano (Grado A)', 'Nike Kyrie 6 Bred', ''),
('Nike (Kobe Bryant)', 'Nike Zoom Kobe Venomenon 5', 40, 7, 239, 'Segunda mano (Grado A)', 'Nike Zoom Kobe Venomenon 5', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 8 Protro Soft Pink', 40, 7, 269, 'Segunda mano (Grado A)', 'Nike Kobe 8 Protro Soft Pink', ''),
('Nike (Kyrie Irving)', 'Concepts x Nike Kyrie 7 Horus T40', 40, 7, 259, 'Segunda mano (Grado A)', 'Concepts x Nike Kyrie 7 Horus T40', ''),
('Nike (LeBron James)', 'Nike LeBron NXXT Gen / 21', 40, 7, 259, 'Segunda mano (Grado A)', 'Nike LeBron NXXT Gen / 21', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Calamardo', 40, 7, 279, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Calamardo', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Hustle', 40, 7, 169, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Hustle', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 4 Keep Sue Fresh', 40.5, 7.5, 219, 'Segunda mano (Grado A)', 'Nike Kyrie Low 4 Keep Sue Fresh', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 11 Elite Low Bruce Lee', 40, 7, 269, 'Segunda mano (Grado A)', 'Nike Kobe 11 Elite Low Bruce Lee', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 6 Prelude', 40, 7, 269, 'Segunda mano (Grado A)', 'Nike Kobe 6 Prelude', ''),
('Nike', 'Nike Kybrid S2 What The USA', 40, 7, 249, 'Segunda mano (Grado A)', 'Kybrid S2 What The USA', ''),
('Nike', 'Nike Kybrid S2 What The Camo', 40, 7, 249, 'Segunda mano (Grado A)', 'Kybrid S2 What The Camo', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 6 Sunset Red', 40, 7, 279, 'Segunda mano (Grado A)', 'Nike Kobe 6 Sunset Red', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 6 Protro Reverse Grinch', 40, 7, 319, 'Segunda mano (Grado A)', 'Nike Kobe 6 Protro Reverse Grinch', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 6 Protro Grinch Verde', 40, 7, 329, 'Segunda mano (Grado A)', 'Nike Kobe 6 Protro Grinch Verde', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 9 Elite Bota Alta', 40, 7, 419, 'Segunda mano (Grado A)', 'Nike Kobe 9 Elite Bota Alta', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 9 Elite Bota Alta', 44, 10, 419, 'Segunda mano (Grado A)', 'Nike Kobe 9 Elite Bota Alta', ''),
('Jordan / Nike', 'Air Jordan 1 Mid Blanco/Sail', 40, 7, 199, 'Segunda mano (Grado A)', 'Air Jordan 1 Mid Blanco/Sail', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 3 Blanco/Azul', 41, 8, 269, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 3 Blanco/Azul', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 3 Blanco/Azul', 43, 9.5, 269, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 3 Blanco/Azul', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 3 Volt', 41, 8, 269, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 3 Volt', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 3 Volt', 43, 9.5, 269, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 3 Volt', ''),
('Jordan / Nike', 'Jordan Luka 1 Blanco/Rosa Origen Nuevo', 41, 8, 269, 'Nuevo / A estrenar', 'Jordan Luka 1 Blanco/Rosa Origen Nuevo', ''),
('Under Armour (Curry)', 'Under Armour Curry Fox 1 Azul', 41, 8, 269, 'Segunda mano (Grado A)', 'Under Armour Curry Fox 1 Azul', ''),
('Under Armour (Curry)', 'Under Armour Curry Fox 1 Azul', 43, 9.5, 269, 'Segunda mano (Grado A)', 'Under Armour Curry Fox 1 Azul', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Casa de Pina SpongeBob', 41, 8, 299, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Casa de Pina SpongeBob', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Casa de Pina SpongeBob', 42, 8.5, 299, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Casa de Pina SpongeBob', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Flytrap 3 Negro/Floral', 41, 8, 169, 'Segunda mano (Grado A)', 'Nike Kyrie Flytrap 3 Negro/Floral', ''),
('adidas', 'adidas Trae Young 3 Gris', 41, 8, 259, 'Segunda mano (Grado A)', 'Trae Young 3 Gris', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 Soundwave Teal', 41, 8, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 Soundwave Teal', ''),
('Puma', 'Puma MB.01 Red Blast RARE', 41, 8, 289, 'Segunda mano (Grado A)', 'MB.01 Red Blast RARE', ''),
('Puma', 'Puma MB.01 Digital Camo', 41, 8, 299, 'Segunda mano (Grado A)', 'MB.01 Digital Camo', ''),
('Nike (Giannis)', 'Nike Giannis Immortality 3 Vino', 41, 8, 219, 'Segunda mano (Grado A)', 'Nike Giannis Immortality 3 Vino', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 5 Orchid Pink', 41, 8, 239, 'Segunda mano (Grado A)', 'Nike Kyrie Low 5 Orchid Pink', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 University Red', 41, 8, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 University Red', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 Daughters', 41, 8, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 Daughters', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 Creator Rayguns', 41, 8, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 Creator Rayguns', ''),
('Nike (Kyrie Irving)', 'Nike Kybrid S2 What The Black', 41, 8, 259, 'Segunda mano (Grado A)', 'Nike Kybrid S2 What The Black', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 4 Confetti Blanco', 41, 8, 269, 'Segunda mano (Grado A)', 'Nike Kyrie 4 Confetti Blanco', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 6 Oreo Blanco/Negro', 41, 8, 279, 'Segunda mano (Grado A)', 'Nike Kyrie 6 Oreo Blanco/Negro', ''),
('Li-Ning', 'Li-Ning Wade All City 10 Cotton Candy', 41, 8, 199, 'Segunda mano (Grado A)', 'Wade All City 10 Cotton Candy', ''),
('Li-Ning', 'Li-Ning Wade All City 8/9', 41, 8, 199, 'Segunda mano (Grado A)', 'Wade All City 8/9', ''),
('Nike (Kevin Durant)', 'Nike KD 13 Blanco/Multicolor', 41, 8, 219, 'Segunda mano (Grado A)', 'Nike KD 13 Blanco/Multicolor', ''),
('Nike (Kyrie Irving)', 'ROKIT x Nike Kyrie 5 All-Star', 41, 8, 229, 'Segunda mano (Grado A)', 'ROKIT x Nike Kyrie 5 All-Star', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Flytrap 2 Negro/Dorado', 41, 8, 189, 'Segunda mano (Grado A)', 'Nike Kyrie Flytrap 2 Negro/Dorado', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 6 There Is No Coming Back', 41, 8, 229, 'Segunda mano (Grado A)', 'Nike Kyrie 6 There Is No Coming Back', ''),
('adidas', 'adidas D Rose 10 Negro/Oro', 41, 8, 229, 'Segunda mano (Grado A)', 'D Rose 10 Negro/Oro', ''),
('Under Armour (Curry)', 'Under Armour Curry 3Z5 Negro/Camo', 41, 8, 219, 'Segunda mano (Grado A)', 'Under Armour Curry 3Z5 Negro/Camo', ''),
('Nike (Kevin Durant)', 'Nike KD 14 Negro/Blanco Strap', 41, 8, 259, 'Segunda mano (Grado A)', 'Nike KD 14 Negro/Blanco Strap', ''),
('adidas', 'adidas Trae Young 1 Negro/Celeste', 41, 8, 249, 'Segunda mano (Grado A)', 'Trae Young 1 Negro/Celeste', ''),
('Li-Ning', 'Li-Ning Sonic 9 Team', 41, 7.5, 179, 'Segunda mano (Grado A)', 'Sonic 9 Team', ''),
('Nike (LeBron James)', 'Nike LeBron XXI Pearl Iridescent', 41, 8, 239, 'Segunda mano (Grado A)', 'Nike LeBron XXI Pearl Iridescent', ''),
('Nike', 'Nike React Hyperdunk 2017 Flyknit', 41, 8, 229, 'Segunda mano (Grado A)', 'React Hyperdunk 2017 Flyknit', ''),
('Puma', 'Puma All-Pro Nitro Rojo/Negro', 41, 8.5, 219, 'Segunda mano (Grado A)', 'All-Pro Nitro Rojo/Negro', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 4 Protro Philly', 41, 8, 279, 'Segunda mano (Grado A)', 'Nike Kobe 4 Protro Philly', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 3 Verde', 41, 8, 269, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 3 Verde', ''),
('Nike (G.T. Series)', 'Nike G.T. Cut 3 Jewell Loyd Smiley', 41, 8, 289, 'Segunda mano (Grado A)', 'Nike G.T. Cut 3 Jewell Loyd Smiley', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 9 EM Low Dust/Gold', 41, 8, 279, 'Segunda mano (Grado A)', 'Nike Kobe 9 EM Low Dust/Gold', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 9 EM Low Black Mamba', 41, 8, 279, 'Segunda mano (Grado A)', 'Nike Kobe 9 EM Low Black Mamba', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 8 Protro Halo Navy', 41, 8, 299, 'Segunda mano (Grado A)', 'Nike Kobe 8 Protro Halo Navy', ''),
('Puma', 'Puma Suede Classic All Black', 41, 8, 169, 'Segunda mano (Grado A)', 'Suede Classic All Black', ''),
('Nike / Jordan', 'Peak Taichi Lou Williams 3', 41, 8, 189, 'Segunda mano (Grado A)', 'Peak Taichi Lou Williams 3', ''),
('Christian Louboutin', 'Christian Louboutin Spikes Slip-on', 41, 8, 259, 'Segunda mano (Grado A)', 'Spikes Slip-on', ''),
('Jordan / Nike', 'Jordan 2x3 Negro/Rojo', 42, 8.5, 219, 'Segunda mano (Grado A)', 'Jordan 2x3 Negro/Rojo', ''),
('Nike (Paul George)', 'Nike PG 6 Oreo', 42, 8.5, 249, 'Segunda mano (Grado A)', 'Nike PG 6 Oreo', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 6 Chinese New Year', 42, 8.5, 249, 'Segunda mano (Grado A)', 'Nike Kyrie 6 Chinese New Year', ''),
('Jordan / Nike', 'Air Jordan 35 Center of Gravity', 42, 8.5, 259, 'Segunda mano (Grado A)', 'Air Jordan 35 Center of Gravity', ''),
('Under Armour (Curry)', 'Under Armour Curry Fox 1 Cyan', 42, 8.5, 259, 'Segunda mano (Grado A)', 'Under Armour Curry Fox 1 Cyan', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Negro/Multicolor', 42, 8.5, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Negro/Multicolor', ''),
('adidas', 'adidas Harden Vol. 7 Puff Melon', 42, 8.5, 279, 'Segunda mano (Grado A)', 'Harden Vol. 7 Puff Melon', ''),
('Jordan / Nike', 'Jordan Luka 2 T42', 42, 8.5, 279, 'Segunda mano (Grado A)', 'Jordan Luka 2 T42', ''),
('Jordan / Nike', 'Jordan Luka 2 T43', 43, 9.5, 279, 'Segunda mano (Grado A)', 'Jordan Luka 2 T43', ''),
('Asics', 'Asics Metarise / Sky Elite Voley', 42, 8.5, 329, 'Segunda mano (Grado A)', 'Metarise / Sky Elite Voley', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Blanco/Teal', 42, 8.5, 249, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Blanco/Teal', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 Daybreak', 42, 8.5, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 Daybreak', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 4 Protro Draft Day Hornets', 42, 8.5, 279, 'Segunda mano (Grado A)', 'Nike Kobe 4 Protro Draft Day Hornets', ''),
('Nike (Paul George)', 'Nike PG 4 Plaid Tartan', 42, 8.5, 209, 'Segunda mano (Grado A)', 'Nike PG 4 Plaid Tartan', ''),
('Jordan / Nike', 'Nike G.T. Cut 3 Jordan Poole PE', 42, 8.5, 279, 'Segunda mano (Grado A)', 'Nike G.T. Cut 3 Jordan Poole PE', ''),
('Jordan / Nike', 'Nike G.T. Cut 3 Jordan Poole PE', 43, 9.5, 279, 'Segunda mano (Grado A)', 'Nike G.T. Cut 3 Jordan Poole PE', ''),
('Nike (G.T. Series)', 'Nike G.T. Cut 3 Glacier Blue', 42, 8.5, 269, 'Segunda mano (Grado A)', 'Nike G.T. Cut 3 Glacier Blue', ''),
('Nike (Kyrie Irving)', 'Concepts x Nike Kyrie 5 Ikhet', 42, 8.5, 269, 'Segunda mano (Grado A)', 'Concepts x Nike Kyrie 5 Ikhet', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 6 Illuminati All-Seeing Eye', 42, 8.5, 279, 'Segunda mano (Grado A)', 'Nike Kyrie 6 Illuminati All-Seeing Eye', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 5 Racer Blue', 42, 8.5, 219, 'Segunda mano (Grado A)', 'Nike Kyrie Low 5 Racer Blue', ''),
('Jordan / Nike', 'Jordan Luka 2 Blanco/Lima', 42, 8.5, 259, 'Segunda mano (Grado A)', 'Jordan Luka 2 Blanco/Lima', ''),
('Jordan / Nike', 'Jordan Luka 2 Lake Bled Turquesa', 42, 8.5, 229, 'Segunda mano (Grado A)', 'Jordan Luka 2 Lake Bled Turquesa', ''),
('Puma', 'Puma Court Rider Chaos Negro/Blanco', 42, 9, 209, 'Segunda mano (Grado A)', 'Court Rider Chaos Negro/Blanco', ''),
('Nike / Jordan', 'Peak Taichi Flash Blanco/Negro', 42, 8.5, 189, 'Segunda mano (Grado A)', 'Peak Taichi Flash Blanco/Negro', ''),
('Li-Ning', 'Li-Ning Combat Low Blanco/Negro', 42, 8.5, 179, 'Segunda mano (Grado A)', 'Combat Low Blanco/Negro', ''),
('Under Armour (Curry)', 'Under Armour Curry Flow 8 White Gold', 42, 8.5, 209, 'Segunda mano (Grado A)', 'Under Armour Curry Flow 8 White Gold', ''),
('Jordan / Nike', 'Air Jordan 34 Eclipse Black White', 42, 8.5, 219, 'Segunda mano (Grado A)', 'Air Jordan 34 Eclipse Black White', ''),
('Nike', 'Off-White x Nike Air Max 90', 42, 8.5, 229, 'Segunda mano (Grado A)', 'Off-White x  Air Max 90', ''),
('adidas', 'adidas Samba OG Blanco/Negro', 42, 8.5, 179, 'Segunda mano (Grado A)', 'Samba OG Blanco/Negro', ''),
('Jordan / Nike', 'Jordan Luka 2 Negro/Volt', 42.5, 9, 299, 'Segunda mano (Grado A)', 'Jordan Luka 2 Negro/Volt', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 4 NCAA White Gum', 42.5, 9, 249, 'Segunda mano (Grado A)', 'Nike Kyrie 4 NCAA White Gum', ''),
('Nike (Kobe Bryant)', 'Nike Kobe AD NXT FastFit', 42.5, 9, 269, 'Segunda mano (Grado A)', 'Nike Kobe AD NXT FastFit', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 4 Blanco/Azul', 42.5, 9, 229, 'Segunda mano (Grado A)', 'Nike Kyrie Low 4 Blanco/Azul', ''),
('Nike (Giannis)', 'Nike Giannis Immortality Negro/Volt', 42.5, 9, 219, 'Segunda mano (Grado A)', 'Nike Giannis Immortality Negro/Volt', ''),
('Anta', 'Anta Shock Wave 4/5 Menta/Naranja', 42.5, 9, 179, 'Segunda mano (Grado A)', 'Shock Wave 4/5 Menta/Naranja', ''),
('Nike (Paul George)', 'Nike PG 4 Triple Black', 42.5, 9, 209, 'Segunda mano (Grado A)', 'Nike PG 4 Triple Black', ''),
('Jordan / Nike', 'Jordan Luka 1 Bred Volt', 42.5, 9, 239, 'Segunda mano (Grado A)', 'Jordan Luka 1 Bred Volt', ''),
('Under Armour (Curry)', 'Under Armour Curry Flow 8 White Black', 42.5, 9, 239, 'Segunda mano (Grado A)', 'Under Armour Curry Flow 8 White Black', ''),
('Jordan / Nike', 'Jordan Zion 3 Blanco/Oro/Rojo', 42.5, 9, 219, 'Segunda mano (Grado A)', 'Jordan Zion 3 Blanco/Oro/Rojo', ''),
('Nike (Paul George)', 'Nike PG 5 Blue Lagoon (Detalle)', 42.5, 9, 169, 'Segunda mano (Grado A)', 'Nike PG 5 Blue Lagoon (Detalle)', ''),
('Nike', 'Nike Initiator Y2K Runner', 42.5, 9, 239, 'Segunda mano (Grado A)', 'Initiator Y2K Runner', ''),
('Jordan / Nike', 'Jordan Luka 1 University Blue', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Jordan Luka 1 University Blue', ''),
('Jordan / Nike', 'Jordan Luka 1 University Blue', 44, 10, 229, 'Segunda mano (Grado A)', 'Jordan Luka 1 University Blue', ''),
('Jordan / Nike', 'Jordan Luka 1 University Blue', 45, 11, 229, 'Segunda mano (Grado A)', 'Jordan Luka 1 University Blue', ''),
('Jordan / Nike', 'Jordan Luka 3 Blanco/Oro/Fucsia', 43, 9.5, 299, 'Segunda mano (Grado A)', 'Jordan Luka 3 Blanco/Oro/Fucsia', ''),
('Jordan / Nike', 'Jordan Luka 3 Midnight Blue/Pink', 43, 9.5, 289, 'Segunda mano (Grado A)', 'Jordan Luka 3 Midnight Blue/Pink', ''),
('Nike (Kevin Durant)', 'Nike KD 15 Neon Multicolor', 43, 9.5, 279, 'Segunda mano (Grado A)', 'Nike KD 15 Neon Multicolor', ''),
('Nike (Ja Morant)', 'Nike Ja 1 Day One Celeste', 43, 9.5, 249, 'Segunda mano (Grado A)', 'Nike Ja 1 Day One Celeste', ''),
('Nike (Ja Morant)', 'Nike Ja 1 EYBL Iridescent', 43, 9.5, 219, 'Segunda mano (Grado A)', 'Nike Ja 1 EYBL Iridescent', ''),
('Puma', 'Puma MB.01 Negro/Rojo Wings', 43, 10, 279, 'Segunda mano (Grado A)', 'MB.01 Negro/Rojo Wings', ''),
('Nike (Giannis)', 'Nike Giannis Freak 6 Blanco/Azul', 43, 9.5, 239, 'Segunda mano (Grado A)', 'Nike Giannis Freak 6 Blanco/Azul', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut Academy Triple Black', 43, 9.5, 219, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut Academy Triple Black', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 Negro/Oro/Amarillo', 43, 9.5, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 Negro/Oro/Amarillo', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 4 Confetti Blanco Multicolor T43', 43, 9.5, 289, 'Segunda mano (Grado A)', 'Nike Kyrie 4 Confetti Blanco Multicolor T43', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 4 BHM Equality T43', 43, 9.5, 269, 'Segunda mano (Grado A)', 'Nike Kyrie 4 BHM Equality T43', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 3 Team Red Hot Punch', 43, 9.5, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 3 Team Red Hot Punch', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 7 1 World 1 People Regal Pink', 43, 9.5, 259, 'Segunda mano (Grado A)', 'Nike Kyrie 7 1 World 1 People Regal Pink', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Blanco/Rojo', 43, 9.5, 249, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Blanco/Rojo', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 5 Protro Hornets Azul/Volt', 43, 9.5, 269, 'Segunda mano (Grado A)', 'Nike Kobe 5 Protro Hornets Azul/Volt', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut 2 Blanco/Celeste', 43, 9.5, 249, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut 2 Blanco/Celeste', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 5 Protro Navy/Volt/Rojo', 43, 9.5, 269, 'Segunda mano (Grado A)', 'Nike Kobe 5 Protro Navy/Volt/Rojo', ''),
('Nike (Kobe Bryant)', 'Nike Kobe AD Exodus Gris/Goma', 43, 9.5, 239, 'Segunda mano (Grado A)', 'Nike Kobe AD Exodus Gris/Goma', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Aluminum/Naranja', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Aluminum/Naranja', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Rosa/Siren Blue', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Rosa/Siren Blue', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Bone Tartan Plaid', 43, 9.5, 239, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Bone Tartan Plaid', ''),
('Nike (LeBron James)', 'Nike LeBron NXXT Gen Celeste/Azul', 43, 9.5, 239, 'Segunda mano (Grado A)', 'Nike LeBron NXXT Gen Celeste/Azul', ''),
('Nike (Paul George)', 'Nike PG 4 Navy Blue', 43, 9.5, 209, 'Segunda mano (Grado A)', 'Nike PG 4 Navy Blue', ''),
('adidas', 'adidas D Rose 11 Blanco/Multicolor', 43, 9.5, 189, 'Segunda mano (Grado A)', 'D Rose 11 Blanco/Multicolor', ''),
('Nike (Ja Morant)', 'Nike Ja 1 Fuel Rojo/Rosa T43', 43, 9.5, 219, 'Segunda mano (Grado A)', 'Nike Ja 1 Fuel Rojo/Rosa T43', ''),
('Nike (Ja Morant)', 'Nike Ja 1 Guava Ice Celeste', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Ja 1 Guava Ice Celeste', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie 5 Blanco/Negro Oreo', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie 5 Blanco/Negro Oreo', ''),
('Jordan / Nike', 'Jordan Jumpman 2021 PF Blanco/Azul', 43, 9.5, 209, 'Segunda mano (Grado A)', 'Jordan Jumpman 2021 PF Blanco/Azul', ''),
('Li-Ning', 'Li-Ning Badfive 3 Low Blanco/Naranja', 43, 9.5, 189, 'Segunda mano (Grado A)', 'Badfive 3 Low Blanco/Naranja', ''),
('Li-Ning', 'Li-Ning Wade All City 9 Blanco/Pastel', 43, 9.5, 189, 'Segunda mano (Grado A)', 'Wade All City 9 Blanco/Pastel', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 5 Coral/Cyan', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie Low 5 Coral/Cyan', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 5 Community Menta/Rosa', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie Low 5 Community Menta/Rosa', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Negro/Blanco/Rojo', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Negro/Blanco/Rojo', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Flytrap 5 Blanco/Gris', 43, 9.5, 199, 'Segunda mano (Grado A)', 'Nike Kyrie Flytrap 5 Blanco/Gris', ''),
('Nike', 'Nike Hyperdunk X EP White Ice Bota', 43, 9.5, 239, 'Segunda mano (Grado A)', 'Hyperdunk X EP White Ice Bota', ''),
('Nike / Jordan', 'adidas Dame 6 Celeste Damian Lillard', 43, 9.5, 179, 'Segunda mano (Grado A)', 'adidas Dame 6 Celeste Damian Lillard', ''),
('Nike (Kevin Durant)', 'Nike Zoom KD 11 Oreo Flyknit', 43, 9.5, 219, 'Segunda mano (Grado A)', 'Nike Zoom KD 11 Oreo Flyknit', ''),
('adidas', 'adidas Pro Bounce 2018 Triple White', 43, 9.5, 189, 'Segunda mano (Grado A)', 'Pro Bounce 2018 Triple White', ''),
('Jordan / Nike', 'Air Jordan 13 Retro Olive Black Suede', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Air Jordan 13 Retro Olive Black Suede', ''),
('Jordan / Nike', 'Air Jordan 1 Mid Panda Black White', 43, 9.5, 229, 'Segunda mano (Grado A)', 'Air Jordan 1 Mid Panda Black White', ''),
('Under Armour (Curry)', 'Under Armour Curry Flow 9 Navy Blue (Horma 43)', 44, 10, 219, 'Segunda mano (Grado A)', 'Under Armour Curry Flow 9 Navy Blue (Horma 43)', ''),
('Nike (Paul George)', 'Nike PG 6 Valentines Day Blanco/Rosa', 44, 10, 279, 'Segunda mano (Grado A)', 'Nike PG 6 Valentines Day Blanco/Rosa', ''),
('Nike (Kevin Durant)', 'Nike KD 14 Negro/Blanco T44', 44, 10, 259, 'Segunda mano (Grado A)', 'Nike KD 14 Negro/Blanco T44', ''),
('Under Armour (Curry)', 'Under Armour Curry 11 Dub Nation Azul/Amarillo', 44, 10, 269, 'Segunda mano (Grado A)', 'Under Armour Curry 11 Dub Nation Azul/Amarillo', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 6 Sunset All-Star T44', 44, 10, 379, 'Precio Interno (En blanco / Consultar)', 'Nike Kobe 6 Sunset All-Star T44', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 4 Protro Girl Dad Bicoastal Green', 44, 10, 279, 'Segunda mano (Grado A)', 'Nike Kobe 4 Protro Girl Dad Bicoastal Green', ''),
('Jordan / Nike', 'Jordan Luka 1 Blanco/Negro/Volt T44', 44, 10, 239, 'Segunda mano (Grado A)', 'Jordan Luka 1 Blanco/Negro/Volt T44', ''),
('Jordan / Nike', 'Jordan Luka 2 Lake Bled Turquesa T44', 44, 10, 239, 'Segunda mano (Grado A)', 'Jordan Luka 2 Lake Bled Turquesa T44', ''),
('Jordan / Nike', 'Jordan Luka 1 Next Nature Blanco/Cyan T44', 44, 10, 239, 'Segunda mano (Grado A)', 'Jordan Luka 1 Next Nature Blanco/Cyan T44', ''),
('Under Armour (Curry)', 'Under Armour Curry 11 Negro/Cyan', 44, 10, 269, 'Segunda mano (Grado A)', 'Under Armour Curry 11 Negro/Cyan', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 4 Protro Mambacita Gigi Blanco/Negro', 44, 10, 289, 'Segunda mano (Grado A)', 'Nike Kobe 4 Protro Mambacita Gigi Blanco/Negro', ''),
('Jordan / Nike', 'Air Jordan 37 Low Dongdan Morado', 44, 10, 229, 'Segunda mano (Grado A)', 'Air Jordan 37 Low Dongdan Morado', ''),
('Jordan / Nike', 'Jordan Jumpman 2021 PF Blanco/Morado', 44, 10, 209, 'Segunda mano (Grado A)', 'Jordan Jumpman 2021 PF Blanco/Morado', ''),
('Nike (Kevin Durant)', 'Nike KD Trey 5 Blanco/Verde', 44, 10, 229, 'Segunda mano (Grado A)', 'Nike KD Trey 5 Blanco/Verde', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 4 Protro x Undefeated Bucks Verde', 44, 10, 289, 'Segunda mano (Grado A)', 'Nike Kobe 4 Protro x Undefeated Bucks Verde', ''),
('Nike (Kobe Bryant)', 'Nike Kobe AD NXT FastFit T44', 44, 10, 289, 'Segunda mano (Grado A)', 'Nike Kobe AD NXT FastFit T44', ''),
('Nike (G.T. Series)', 'Nike G.T. Hustle Blanco/Rojo T44', 44, 10, 239, 'Segunda mano (Grado A)', 'Nike G.T. Hustle Blanco/Rojo T44', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Low 2 Blanco/Rojo/Azul', 44, 10, 219, 'Segunda mano (Grado A)', 'Nike Kyrie Low 2 Blanco/Rojo/Azul', ''),
('Nike (Giannis)', 'Nike Giannis Immortality 2 Blanco/Rosa', 44, 10, 179, 'Segunda mano (Grado A)', 'Nike Giannis Immortality 2 Blanco/Rosa', ''),
('Jordan / Nike', 'Off-White x Air Jordan 4 Sail', 44, 10, 269, 'Segunda mano (Grado A)', 'Off-White x Air Jordan 4 Sail', ''),
('Nike', 'Nike Air Monarch IV Blanco/Negro', 44, 10, 169, 'Segunda mano (Grado A)', 'Air Monarch IV Blanco/Negro', ''),
('Nike (LeBron James)', 'Nike LeBron 20 All-Star Rosa/Cyan', 44, 10, 199, 'Segunda mano (Grado A)', 'Nike LeBron 20 All-Star Rosa/Cyan', ''),
('Jordan / Nike', 'Jordan Luka 3 Amarillo/Negro', 44.5, 10.5, 289, 'Segunda mano (Grado A)', 'Jordan Luka 3 Amarillo/Negro', ''),
('Nike (G.T. Series)', 'Nike G.T. Hustle 3 Rojo/Blanco', 44.5, 10.5, 249, 'Segunda mano (Grado A)', 'Nike G.T. Hustle 3 Rojo/Blanco', ''),
('Nike (Kevin Durant)', 'Nike KD Trey 5 IX Gris/Naranja', 44.5, 10.5, 219, 'Segunda mano (Grado A)', 'Nike KD Trey 5 IX Gris/Naranja', ''),
('Nike (Giannis)', 'Nike Zoom Freak 4 Blanco/Menta', 44.5, 10.5, 239, 'Segunda mano (Grado A)', 'Nike Zoom Freak 4 Blanco/Menta', ''),
('Jordan / Nike', 'Jordan Luka 3 Blanco/Teal con Caja', 44.5, 10.5, 379, 'Nuevo / A estrenar', 'Jordan Luka 3 Blanco/Teal con Caja', ''),
('Nike (G.T. Series)', 'Nike Air Zoom G.T. Cut Academy Blanco/Rojo', 45, 11, 249, 'Segunda mano (Grado A)', 'Nike Air Zoom G.T. Cut Academy Blanco/Rojo', ''),
('Nike (Kobe Bryant)', 'Nike Kobe 5 Protro Navy/Volt T45', 45, 11, 259, 'Segunda mano (Grado A)', 'Nike Kobe 5 Protro Navy/Volt T45', ''),
('Jordan / Nike', 'Jordan Luka 1 Rosa/Blanco', 45, 11, 229, 'Segunda mano (Grado A)', 'Jordan Luka 1 Rosa/Blanco', ''),
('Nike (Paul George)', 'Nike Precision 6 Blanco/Rojo Floral', 45, 11, 179, 'Segunda mano (Grado A)', 'Nike Precision 6 Blanco/Rojo Floral', ''),
('Under Armour (Curry)', 'Under Armour Curry 7 Blanco/Negro', 45, 11, 219, 'Segunda mano (Grado A)', 'Under Armour Curry 7 Blanco/Negro', ''),
('Jordan / Nike', 'Jordan Zion 1 Verde Militar/Goma', 45, 11, 219, 'Segunda mano (Grado A)', 'Jordan Zion 1 Verde Militar/Goma', ''),
('Nike (Kyrie Irving)', 'Nike Kyrie Infinity Gris/Amarillo/Multi', 45, 11, 249, 'Segunda mano (Grado A)', 'Nike Kyrie Infinity Gris/Amarillo/Multi', ''),
('Nike (Kyrie Irving)', 'Rigorer / Kyrie Low Azul/Naranja', 45, 11, 159, 'Segunda mano (Grado A)', 'Rigorer / Kyrie Low Azul/Naranja', ''),
('Anta', 'Anta Shock Wave Menta/Gris/Verde', 45, 11, 179, 'Segunda mano (Grado A)', 'Shock Wave Menta/Gris/Verde', '');