-- 1. Añadir columna para múltiples imágenes (arreglo de textos)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS galeria TEXT[] DEFAULT '{}';

-- 2. Crear tabla de ventas
CREATE TABLE IF NOT EXISTS public.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    marca TEXT,
    modelo TEXT,
    precio_venta NUMERIC NOT NULL,
    costo NUMERIC NOT NULL,
    ganancia NUMERIC NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Políticas de seguridad (RLS) para tabla de ventas
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin All Access Ventas" ON public.ventas FOR ALL TO authenticated USING (true);
